# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: brutal-db
    environment:
      POSTGRES_DB: brutal
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5432"   # ← Expose to host so your Go app can connect
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: